framework:
    rate_limiter:
        like_action:
            policy: 'sliding_window'
            limit: 30
            interval: '1 minute'
        comment_action:
            policy: 'sliding_window'
            limit: 10
            interval: '1 minute'
        reaction_action:
            policy: 'sliding_window'
            limit: 30
            interval: '1 minute'
